// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJ5PUwX3MjytgV3mrez_q8H5fd4JwSaQ',
    appId: '1:1071802428276:web:6c7be06b2b7c59278d9a21',
    messagingSenderId: '1071802428276',
    projectId: 'newsapp5-d0ca5',
    authDomain: 'newsapp5-d0ca5.firebaseapp.com',
    storageBucket: 'newsapp5-d0ca5.appspot.com',
  );

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeoygccxL4iSvz4SV3xmWQZ7vhEvegts',
    appId: '1:1071802428276:android:fd0b8cbb21d22d3f8d9a21',
    messagingSenderId: '1071802428276',
    projectId: 'newsapp5-d0ca5',
    storageBucket: 'newsapp5-d0ca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnHKRCD8zfnJVMbG0__yY7PVlIoMhwN4',
    appId: '1:1071802428276:ios:bff6765154b9cf3e8d9a21',
    messagingSenderId: '1071802428276',
    projectId: 'newsapp5-d0ca5',
    storageBucket: 'newsapp5-d0ca5.appspot.com',
    iosBundleId: 'com.example.newsapp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPnHKRCD8zfnJVMbG0__yY7PVlIoMhwN4',
    appId: '1:1071802428276:ios:bff6765154b9cf3e8d9a21',
    messagingSenderId: '1071802428276',
    projectId: 'newsapp5-d0ca5',
    storageBucket: 'newsapp5-d0ca5.appspot.com',
    iosBundleId: 'com.example.newsapp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUJ5PUwX3MjytgV3mrez_q8H5fd4JwSaQ',
    appId: '1:1071802428276:web:154780e4d49c96778d9a21',
    messagingSenderId: '1071802428276',
    projectId: 'newsapp5-d0ca5',
    authDomain: 'newsapp5-d0ca5.firebaseapp.com',
    storageBucket: 'newsapp5-d0ca5.appspot.com',
  );

}